FROM debian:9.11-slim

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
        curl \
        ca-certificates

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh \
        && bash rustup.sh -y --profile minimal

RUN curl --proto '=https' -sSf \
            https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz > go.tar.gz \
        && tar -C /usr/local -xzf go.tar.gz

ENV PATH "/usr/local/go/bin:/root/.cargo/bin:$PATH"
